version: '3'

services:
  db:
    image: mongo
    container_name: mongodbcontainer
    ports:
      - 27017:27017
    volumes:
      - mongovolume:/data/db
    
  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  mongovolume:
    