name: CD Pipeline to deploy backend on EC2
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]

jobs:
  Deploy-To-DockerHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ github.sha }}

  Host-on-EC2:
    needs: Deploy-To-DockerHub
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is working fine"